# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: skip-file
# flake8: noqa

from azure.cli.core.aaz import *


@register_command(
    "database-fleet-manager fleet fleetspace database create",
    is_preview=True,
)
class Create(AAZCommand):
    """Create a fleet database.
    """

    _aaz_info = {
        "version": "2023-08-01-preview",
        "resources": [
            ["mgmt-plane", "/subscriptions/{}/resourcegroups/{}/providers/microsoft.databasefleetmanager/fleets/{}/fleetspaces/{}/databases/{}", "2023-08-01-preview"],
        ]
    }

    AZ_SUPPORT_NO_WAIT = True

    def _handler(self, command_args):
        super()._handler(command_args)
        return self.build_lro_poller(self._execute_operations, self._output)

    _args_schema = None

    @classmethod
    def _build_arguments_schema(cls, *args, **kwargs):
        if cls._args_schema is not None:
            return cls._args_schema
        cls._args_schema = super()._build_arguments_schema(*args, **kwargs)

        # define Arg Group ""

        _args_schema = cls._args_schema
        _args_schema.database_name = AAZStrArg(
            options=["-n", "--name", "--database-name"],
            required=True,
            fmt=AAZStrArgFormat(
                pattern="^(?!.*--)[a-z0-9]+(?:-[a-z0-9]+)*$",
            ),
        )
        _args_schema.fleet_name = AAZStrArg(
            options=["--fleet-name"],
            required=True,
            fmt=AAZStrArgFormat(
                pattern="^(?!.*--)[a-z0-9]+(?:-[a-z0-9]+)*$",
            ),
        )
        _args_schema.fleetspace_name = AAZStrArg(
            options=["--fleetspace-name"],
            required=True,
            fmt=AAZStrArgFormat(
                pattern="^(?!.*--)[a-z0-9]+(?:-[a-z0-9]+)*$",
            ),
        )
        _args_schema.resource_group = AAZResourceGroupNameArg(
            required=True,
        )

        # define Arg Group "Parameters"

        _args_schema = cls._args_schema
        _args_schema.location = AAZResourceLocationArg(
            arg_group="Parameters",
            fmt=AAZResourceLocationArgFormat(
                resource_group_arg="resource_group",
            ),
        )
        _args_schema.tags = AAZDictArg(
            options=["--tags"],
            arg_group="Parameters",
        )

        tags = cls._args_schema.tags
        tags.Element = AAZStrArg()

        # define Arg Group "Properties"

        _args_schema = cls._args_schema
        _args_schema.additional_db_properties = AAZDictArg(
            options=["--additional-db-properties"],
            arg_group="Properties",
        )
        _args_schema.create_mode = AAZStrArg(
            options=["--create-mode"],
            arg_group="Properties",
            help="Create mode. Always default (To do, add modes).",
            enum={"Copy": "Copy", "Default": "Default", "PointInTimeRestore": "PointInTimeRestore"},
        )
        _args_schema.name_seed = AAZStrArg(
            options=["--name-seed"],
            arg_group="Properties",
            help="Name seed for autogenerated names.",
        )
        _args_schema.restore_from_time = AAZDateTimeArg(
            options=["--restore-from-time"],
            arg_group="Properties",
            help="Restore from time when CreateMode is PointInTimeRestore.",
        )
        _args_schema.source_database_name = AAZStrArg(
            options=["--source-database-name"],
            arg_group="Properties",
            help="Source database name used when CreateMode is Copy or PointInTimeRestore.",
        )
        _args_schema.tier_name = AAZStrArg(
            options=["--tier-name"],
            arg_group="Properties",
            help="Name of the tier this database belongs to.",
        )

        additional_db_properties = cls._args_schema.additional_db_properties
        additional_db_properties.Element = AAZStrArg()
        return cls._args_schema

    def _execute_operations(self):
        self.pre_operations()
        yield self.FleetDatabaseCreateDatabase(ctx=self.ctx)()
        self.post_operations()

    @register_callback
    def pre_operations(self):
        pass

    @register_callback
    def post_operations(self):
        pass

    def _output(self, *args, **kwargs):
        result = self.deserialize_output(self.ctx.vars.instance, client_flatten=True)
        return result

    class FleetDatabaseCreateDatabase(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [202]:
                return self.client.build_lro_polling(
                    self.ctx.args.no_wait,
                    session,
                    self.on_200_201,
                    self.on_error,
                    lro_options={"final-state-via": "azure-async-operation"},
                    path_format_arguments=self.url_parameters,
                )
            if session.http_response.status_code in [200, 201]:
                return self.client.build_lro_polling(
                    self.ctx.args.no_wait,
                    session,
                    self.on_200_201,
                    self.on_error,
                    lro_options={"final-state-via": "azure-async-operation"},
                    path_format_arguments=self.url_parameters,
                )

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DatabaseFleetManager/fleets/{fleetName}/fleetspaces/{fleetspaceName}/databases/{databaseName}",
                **self.url_parameters
            )

        @property
        def method(self):
            return "PUT"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "databaseName", self.ctx.args.database_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "fleetName", self.ctx.args.fleet_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "fleetspaceName", self.ctx.args.fleetspace_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "resourceGroupName", self.ctx.args.resource_group,
                    required=True,
                ),
                **self.serialize_url_param(
                    "subscriptionId", self.ctx.subscription_id,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2023-08-01-preview",
                    required=True,
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Content-Type", "application/json",
                ),
                **self.serialize_header_param(
                    "Accept", "application/json",
                ),
            }
            return parameters

        @property
        def content(self):
            _content_value, _builder = self.new_content_builder(
                self.ctx.args,
                typ=AAZObjectType,
                typ_kwargs={"flags": {"required": True, "client_flatten": True}}
            )
            _builder.set_prop("location", AAZStrType, ".location")
            _builder.set_prop("properties", AAZObjectType)
            _builder.set_prop("tags", AAZDictType, ".tags")

            properties = _builder.get(".properties")
            if properties is not None:
                properties.set_prop("additionalDbProperties", AAZDictType, ".additional_db_properties")
                properties.set_prop("createMode", AAZStrType, ".create_mode")
                properties.set_prop("nameSeed", AAZStrType, ".name_seed")
                properties.set_prop("restoreFromTime", AAZStrType, ".restore_from_time")
                properties.set_prop("sourceDatabaseName", AAZStrType, ".source_database_name")
                properties.set_prop("tierName", AAZStrType, ".tier_name")

            additional_db_properties = _builder.get(".properties.additionalDbProperties")
            if additional_db_properties is not None:
                additional_db_properties.set_elements(AAZStrType, ".")

            tags = _builder.get(".tags")
            if tags is not None:
                tags.set_elements(AAZStrType, ".")

            return self.serialize_content(_content_value)

        def on_200_201(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200_201
            )

        _schema_on_200_201 = None

        @classmethod
        def _build_schema_on_200_201(cls):
            if cls._schema_on_200_201 is not None:
                return cls._schema_on_200_201

            cls._schema_on_200_201 = AAZObjectType()

            _schema_on_200_201 = cls._schema_on_200_201
            _schema_on_200_201.id = AAZStrType(
                flags={"read_only": True},
            )
            _schema_on_200_201.location = AAZStrType()
            _schema_on_200_201.name = AAZStrType(
                flags={"read_only": True},
            )
            _schema_on_200_201.properties = AAZObjectType()
            _schema_on_200_201.tags = AAZDictType()
            _schema_on_200_201.type = AAZStrType(
                flags={"read_only": True},
            )

            properties = cls._schema_on_200_201.properties
            properties.additional_db_properties = AAZDictType(
                serialized_name="additionalDbProperties",
            )
            properties.backup_retention_days = AAZIntType(
                serialized_name="backupRetentionDays",
                flags={"read_only": True},
            )
            properties.connection_string = AAZStrType(
                serialized_name="connectionString",
                flags={"read_only": True},
            )
            properties.create_mode = AAZStrType(
                serialized_name="createMode",
            )
            properties.database_size_gb_max = AAZIntType(
                serialized_name="databaseSizeGbMax",
                flags={"read_only": True},
            )
            properties.earliest_restore_time = AAZStrType(
                serialized_name="earliestRestoreTime",
                flags={"read_only": True},
            )
            properties.latest_restore_time = AAZStrType(
                serialized_name="latestRestoreTime",
                flags={"read_only": True},
            )
            properties.name_seed = AAZStrType(
                serialized_name="nameSeed",
            )
            properties.original_database_id = AAZStrType(
                serialized_name="originalDatabaseId",
                flags={"read_only": True},
            )
            properties.provisioning_state = AAZStrType(
                serialized_name="provisioningState",
                flags={"read_only": True},
            )
            properties.recoverable = AAZBoolType(
                flags={"read_only": True},
            )
            properties.restore_from_time = AAZStrType(
                serialized_name="restoreFromTime",
            )
            properties.source_database_name = AAZStrType(
                serialized_name="sourceDatabaseName",
            )
            properties.tier_name = AAZStrType(
                serialized_name="tierName",
            )

            additional_db_properties = cls._schema_on_200_201.properties.additional_db_properties
            additional_db_properties.Element = AAZStrType()

            tags = cls._schema_on_200_201.tags
            tags.Element = AAZStrType()

            return cls._schema_on_200_201


class _CreateHelper:
    """Helper class for Create"""


__all__ = ["Create"]
